initial_position:
  - 0.35
  - -0.55
  - 0.25
  - 3.14
  - 0
  - 0
# the numebr of sampled points is cube_size*cube_size*cube_size
cube_size: 4
x_stride: 0.05
y_stride: 0.05
z_stride: 0.02
#cube_size: 2
#x_stride: 0.1
#y_stride: 0.1
#z_stride: 0.04
CALIBRATION_DIR: "/data/calibration_data/ur10e-kinect.npz"
OFFSET: 0.16
