site_name: DeepClaw
nav:
    - Home:
      - Overview: index.md
      - Installation: install.md
    - Manual: 
      - DeepClaw Pipeline: pipeline.md
      - Robot Library: robot.md
      - Model Zoo: model.md
      - Task Family: task.md
      # - Sim-2-Real (TODO): sim2real.md
    - Notes:
      - For Developers: devnote.md
      # - For Users (TODO): usenote.md
theme: readthedocs