# initial params
HOME_POSE:
  -
    - 0.1
    - 0.1
    - 0.15
  -
    - 3.14
    - 0
    - 0
PICK_Z: 0.07
PLACE_Z: 0.08

# calibrating params
# [[0.2, 0.05, 0.15], [pi/2.0, pi/2.0, pi/2.0]]
initial_pose:
  -
    - 0.2
    - 0.05
    - 0.15
  -
    - 1.57
    - 1.57
    - 1.57
x_step_length: 0.01
y_step_length: 0.01
z_step_length: 0.01