# initial params
SOCKET_CONFIGURATION:
  robot_ip: "192.168.1.27"
  port_number: 30003

HOME_JOINTS:
  - -66.92
  - -62.26
  - -115.08
  - -92.58
  - 89.31
  - 203.1

HOME_POSE:
  - 0.012
  - -0.3085
  - 0.4
  - 3.14
  - 0
  - 0
PICK_Z: 0.
PLACE_Z: 0.08
CALIBRATION_DIR: "/data/calibration_data/ur5.npz"

