# initial params
SOCKET_CONFIGURATION:
  robot_ip: "192.168.1.27"
  port_number: 30003

HOME_JOINTS:
  - -66.93
  - -64.87
  - -98.95
  - -106.39
  - 89.32
  - 23.23

HOME_POSE:
  - 0.0128
  - -0.31041
  - 0.49931
  - 3.139
  - -0.0002
  - -3.142
PICK_Z: 0.
PLACE_Z: 0.08
CALIBRATION_DIR: "/data/calibration_data/ur5.npz"

