# initial params
SOCKET_CONFIGURATION:
  robot_ip: "192.168.1.27"
  port_number: 30003

HOME_JOINTS:
  - -68.57
  - -64.48
  - -101.10
  - -104.38
  - 89.44
  - 111.62

HOME_POSE:
  - 0.012
  - -0.3085
  - 0.46689
  - 3.14
  - 0
  - 0
PICK_Z: 0.34
PLACE_Z: 0.40
CALIBRATION_DIR: "/data/calibration_data/ur5-realsense.npz"

